### PR TITLE
Update to PMP PHP SDK 2.0.0

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Removes support for PHP versions before 5.5, and sets a `Requires PHP: 5.5` flag in `readme.txt`.
- Updates to [PMP PHP SDK version 2.0.2](https://github.com/npr/pmp-php-sdk/releases/tag/v2.0.2). (Pull request [#143](https://github.com/npr/pmp-wordpress-plugin/pull/143) for issue [#142](https://github.com/npr/pmp-wordpress-plugin/issues/142)) and [#145](https://github.com/npr/pmp-wordpress-plugin/issues/145). Changes affecting this plugin are as follows:
	- Upgrades to Guzzle 6
	- Adds support for PHP 7.0 and later
	- Removes support for PHP versions before 5.5
	- Provides a new-and-updated PHAR file to bundle in this plugin
- Bumps "Tested up to:" in `README.txt` from 4.3 to 4.9
- Adds "Requires PHP: 5.5" in `README.txt` to match the requirement in PMP PHP SDK
- Bumps "Requires at least:" in `README.txt` from 3.9 to 4.1, because we're no longer running tests against 3.9 or 4.0 after PR #136.
- Fixes the official plugin URL in `docs/installation.md`
- Changes the message displayed in the settings page during a PMP PHP SDK `AuthException` to "Unable to connect - invalid Client-Id/Secret. Is the correct environment chosen?" because that's a simple and easy mistake to make.
- Reorders tests to run PHP versions in decreasing order, to provide earlier feedback for broken tests in PHP 7.
- Fixes some tests broken by https://github.com/npr/pmp-wordpress-plugin/pull/146 that we didn't catch at the time, because of the SDK throwing errors in PHP 7 and those tests would have run after the SDK tests ran.

## Why

https://github.com/npr/pmp-wordpress-plugin/issues/142 is the ticket for tracking updating to PMP PHP SDK 2.0.0, but this arises from an issue identified in https://github.com/npr/pmp-wordpress-plugin/pull/136 with the PMP PHP SDK erroring out during JSON decode errors in DELETE requests, documented at https://github.com/npr/pmp-php-sdk/issues/37. The fix has been made in the SDK; now we import it to the plugin.

#142 was originally to update to 2.0.0, but we're going with 2.0.2 because it's most recent.

### CODE REVIEW

**Comment by benlk** [comment]
This is blocked by https://github.com/npr/pmp-wordpress-plugin/issues/133.

**Comment by benlk** [comment]
Getting this in all PHP 7 versions:

> Fatal error: Uncaught Pmp\Sdk\Exception\RemoteException: [204]: JSON decode error => DELETE https://publish-sandbox.pmp.io/docs/a3ba7eba-9448-4921-87b5-2e0c0a8e96a1
  thrown in phar:///tmp/wordpress/src/wp-content/plugins/pmp-wordpress-plugin/vendor/pmpsdk.phar/Pmp/Sdk/Http.php on line 179
> Pmp\Sdk\Exception\RemoteException: JSON decode error in phar:///tmp/wordpress/src/wp-content/plugins/pmp-wordpress-plugin/vendor/pmpsdk.phar/Pmp/Sdk/Http.php on line 179

This would appear to be because Travis is using the bundled `pmpsdk.phar` in this plugin, rather than the `composer`-required file.

**Comment by benlk** [comment]
To fix the "bundled .phar" problem:

- [ ] remove `vendor/pmpsdk.phar`, because that file is out of date and no longer supported by the PMP PHP SDK, as described at https://github.com/npr/pmp-php-sdk/releases/tag/v2.0.0. This means that people who download the plugin from GitHub must run `composer install` in order to acquire the SDK files.
- [ ] provide instructions to users on who download the plugin directly from GitHub on how they can run `composer install` and `bower install`.
- [ ] update tests so that Travis's test suite will run `composer install`.
- [ ] make sure that `release.sh` is up-to-date with https://github.com/INN/docs/blob/master/projects/wordpress-plugins/release.sh and that it correctly bundles the vendor dependencies in the release `.zip`.

**Comment by scottsmith130** [comment]
We're looking into bringing back phar packaging in the SDK

**Comment by benlk** [comment]
@scottsmith130 is there support for the phar package in SDK 2.0.1? I didn't see anything about it in the release notes.

**Comment by scottsmith130** [comment]
@benlk no, phar is not in 2.0.1.  Hoping to have it ready in 2.0.2.

**Comment by scottsmith130** [comment]
@benlk SDK 2.0.2 is released, it has phar support now

**Comment by benlk** [comment]
I'm not sure, but I think the build server has been running against weird merges rather than this PR's proposed merge. Continuing to investigate.

**Comment by benlk** [comment]
It was running against this PR's proposed merge; I was confused by too many builds enqueued at once running similarly-named tests outputting similar errors.

Tests pass!

And I'm able to pull from the API successfully.

Pushed https://support.pmp.io/search?text=guid%3A435dcb6f-dd49-4108-a15e-ab1d5f89b940 to the PMP API without errors, though it's hidden, probably because it was pushed in group "test group 2" in series "Test Series".

When pushing, I received the following server log:

> PHP message: [PMP_DEBUG] -- pushing wp[22]
> PHP message: [PMP_DEBUG]    ** newing a doc wp[22]
> PHP message: [PMP_DEBUG]    -- pushing wp[24]
> PHP message: [PMP_DEBUG]       ** newing a doc wp[24]

22 is the ID of the post I pushed; 24 is the ID of the image used as the post's thumbnail.

**Pull request merged**
